SET search_path TO thiqah, public;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'thiqah_app') THEN
    CREATE ROLE thiqah_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA thiqah TO thiqah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA thiqah TO thiqah_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA thiqah TO thiqah_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA thiqah TO thiqah_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA thiqah GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thiqah_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA thiqah GRANT USAGE, SELECT ON SEQUENCES TO thiqah_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA thiqah GRANT EXECUTE ON FUNCTIONS TO thiqah_app;
